kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
  labels:
    type: local
spec:
  storageClassName: nfs-link
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nfs_test"
